kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-binding
  namespace: tiller-land
subjects:
- kind: ServiceAccount
  name: tiller-sa
  namespace: tiller-land
roleRef:
  kind: Role
  name: tiller-role
  apiGroup: rbac.authorization.k8s.io
